name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build -t kurt91932/wine_classification .

    - name: Push Docker Image
      run: |
        echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
        docker push kurt91932/wine_classification

    - name: Deploy to Heroku
      run: |
        echo ${{secrets.HEROKU_API_KEY}} | docker login --username=_ --password-stdin registry.heroku.com
        heroku container:push web --app wine_classification